# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: trading-bot-service
  namespace: trading
spec:
  selector:
    app: trading-bot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP